- hosts: localhost
  roles:
         # Loads library/openshift.py to make it available to other plays;
         # does nothing else by itself
         - { role: epfl_idevelop.ansible_module_openshift }

  tasks:       
    - name: deploy_wp
      include_role:
        name: "{{item.type}}"
      vars:
        app_name: "{{item.name}}"
        db_name: "{{item.db_name}}"
        db_ip: "{{item.db_ip}}"
        db_root_password: "{{item.db_root_password}}"
        nfs_ip: "{{item.nfs_ip}}"
      loop:
        - { name: 'wp1', type: 'wordpress', db_name: 'db_wp1', db_ip: '128.179.146.8', nfs_ip: '128.179.146.8', db_root_password: 'ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAksw5Hr8L9P5ybvD85NEl9DU3Ow9HtKgY8llaFwygoS+uvs1+4ZDKTJSQ+stDMn0HsVEqgEC7S2TQL9aS/FbeViSp1ixV0pekRhWj7sQ7T/Al9TaPBPm6EfI6vTwF8yTO68arEylIwLCsz+2CFCGmrmzDJNd9TrSpx2YHUaFaMEuFvaix1XjDW9+/5LtUY0BKAvHsz38j6j3oUHhX8an/cJRVTMavfpB6Xkd0eM365wa5ztwFEv8dO+pHs6L1Sxie8H4ClqsDUrY71sWLpar3+AuBgUUhsg87xW94OjSmeVfFT3U6o1DTBZihMronIdlHqIyE5k/3RMrwF2UqVgZeNjA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBA7EFlCuAxRnJ/w0XyducVhgBB61WxAO+a7GWBvwK+/UczL]'}
        - { name: 'wp2', type: 'wordpress', db_name: 'db_wp2', db_ip: '128.179.146.8', nfs_ip: '128.179.146.8', db_root_password: 'ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAksw5Hr8L9P5ybvD85NEl9DU3Ow9HtKgY8llaFwygoS+uvs1+4ZDKTJSQ+stDMn0HsVEqgEC7S2TQL9aS/FbeViSp1ixV0pekRhWj7sQ7T/Al9TaPBPm6EfI6vTwF8yTO68arEylIwLCsz+2CFCGmrmzDJNd9TrSpx2YHUaFaMEuFvaix1XjDW9+/5LtUY0BKAvHsz38j6j3oUHhX8an/cJRVTMavfpB6Xkd0eM365wa5ztwFEv8dO+pHs6L1Sxie8H4ClqsDUrY71sWLpar3+AuBgUUhsg87xW94OjSmeVfFT3U6o1DTBZihMronIdlHqIyE5k/3RMrwF2UqVgZeNjA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBA7EFlCuAxRnJ/w0XyducVhgBB61WxAO+a7GWBvwK+/UczL]'}
        - { name: 'mgmt', type: 'mgmt', db_ip: '128.179.146.8', nfs_ip: '128.179.146.8'}