
- name: pv
  import_tasks: "pl_pv.yml"
  when: state == 'latest' or state == 'present'

- name: pvc
  import_tasks: "pl_pvc.yml"
  when: state == 'latest' or state == 'present'

- name: OpenProject deployment
  import_tasks: "pl_opp_dc.yml"

- name: OpenProject service
  import_tasks: "pl_opp_svc.yml"

- name: OpenProject route
  import_tasks: "pl_opp_rt.yml"

- name: pvc
  import_tasks: "pl_pvc.yml"
  when: state == 'absent'

- name: pv
  import_tasks: "pl_pv.yml"
  when: state == 'absent'
