---
# vars file for openproject-role

#db_root_password: ENC[PKCS7,MIIBeQYJKoZIhvcNAQcDoIIBajCCAWYCAQAxggEhMIIBHQIBADAFMAACAQEwDQYJKoZIhvcNAQEBBQAEggEAksw5Hr8L9P5ybvD85NEl9DU3Ow9HtKgY8llaFwygoS+uvs1+4ZDKTJSQ+stDMn0HsVEqgEC7S2TQL9aS/FbeViSp1ixV0pekRhWj7sQ7T/Al9TaPBPm6EfI6vTwF8yTO68arEylIwLCsz+2CFCGmrmzDJNd9TrSpx2YHUaFaMEuFvaix1XjDW9+/5LtUY0BKAvHsz38j6j3oUHhX8an/cJRVTMavfpB6Xkd0eM365wa5ztwFEv8dO+pHs6L1Sxie8H4ClqsDUrY71sWLpar3+AuBgUUhsg87xW94OjSmeVfFT3U6o1DTBZihMronIdlHqIyE5k/3RMrwF2UqVgZeNjA8BgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBA7EFlCuAxRnJ/w0XyducVhgBB61WxAO+a7GWBvwK+/UczL]

eyaml_keys:
  priv: "/keybase/team/epfl_wwp_blue/private_key.pkcs7.pem"
  pub: "/keybase/team/epfl_wwp_blue/public_key.pkcs7.pem"