---

- name: "deployment config"
  openshift:
    state: "{{state}}"
    kind: DeploymentConfig
    name: "{{app_name}}"
    namespace: "myproject"
    apiVersion: "v1"
    metadata:
      labels:
        run: "{{app_name}}"
      name: "{{app_name}}"
      namespace: myproject
    spec:
      replicas: "{{replicas}}"
      selector:
        run: "{{app_name}}"
      template:
        metadata:
          labels:
            run: "{{app_name}}"
        spec:
          containers:
            - image: ubuntu
              name: "{{app_name}}"
              tty: true
              volumeMounts:
                - mountPath: /usr/share/ops
                  name: nfsvol-mgmt
          volumes:
            - name: nfsvol-mgmt
              persistentVolumeClaim:
                claimName: nfs-pvc-mgmt
      triggers:
        - type: ConfigChange
  tags: dc
