---
- name: "PersistentVolumeClaim"
  openshift:
    as_admin: true
    state: "{{state}}"
    kind: PersistentVolumeClaim
    name: "nfs-pvc-mgmt"
    namespace: "myproject"
    apiVersion: v1
    metadata:
      name: nfs-pvc-mgmt
    spec:
      accessModes:
      - ReadWriteMany
      resources:
         requests:
           storage: 1Gi
      selector:
          matchLabels:
              id: mgmt
  tags: pvc