---

- name: "deployment config"
  openshift:
    state: "{{state}}"
    kind: DeploymentConfig
    name: "{{app_name}}"
    namespace: "myproject"
    apiVersion: apps.openshift.io/v1
    metadata:
      labels:
        run: "{{app_name}}"
      name: "{{app_name}}"
      namespace: myproject
    spec:
      replicas: "{{replicas}}"
      revisionHistoryLimit: 10
      selector:
        run: "{{app_name}}"
      template:
        metadata:
          labels:
            run: "{{app_name}}"
        spec:
          containers:
            - env:
                - name: WORDPRESS_DB_NAME
                  value: db1
                - name: WORDPRESS_DB_USER
                  value: root
                - name: WORDPRESS_DB_PASSWORD
                  value: root!
                - name: WORDPRESS_DB_HOST
                  value: 128.179.178.87
              image: 'wordpress:latest'
              name: "{{app_name}}"
              volumeMounts:
                - mountPath: /usr/share/ops
                  name: nfsvol-2
          volumes:
            - name: nfsvol-2
              persistentVolumeClaim:
                claimName: nfs-pvc
      triggers:
        - type: ConfigChange
  tags: dc
